### ISSUE TITLE
Inconsistent values for Q30 between two different views.

### ISSUE THREAD

**Issue by yechenqiao** [Illumina/interop#106]
Hi,
Sometimes Q30 values printed from collapsed metrics can differ significantly from the summary statistics:
If you look at the Q30 value of:
https://basespace.illumina.com/run/14858869/HiSeq-2500-v2-TruSeq-Exome-9-replicates-of-NA12878

On Lane 2: the collapsed q-metrics (.cpp, dumptext binary) reported a percentage of 89.4% after division. However, the summary statistics reported it as 96.36%.  (summary binary)

Currently, this issue can also be seen in either the basespace page and the sequence analysis viewer. If you use SAV analysis tab and look at read 2 for all (lane, surface, cycle), you'd see (Q>=30)=89.4%. However if you look at Summary tab: Level Read 2 (I) is reported as having (%>=Q30)=96.36%. Are there any reasons these two values are different?

![sav_q30_analysis](https://cloud.githubusercontent.com/assets/13461536/23755169/78ccddb0-04ad-11e7-9413-16c52f4f19c9.PNG)
![sav_q30_summary](https://cloud.githubusercontent.com/assets/13461536/23755186/846c4f70-04ad-11e7-8269-1c381bc23a3d.PNG)

Thanks!

**Comment by yechenqiao** [comment]
Upon further investigation: it seems this is related to line 192 of 
https://github.com/Illumina/interop/blob/master/interop/logic/summary/quality_summary.h

 if(cycle_to_read[beg->cycle()-1].is_last_cycle_in_read) continue;

Seems to be skipping last cycle for each read when computing Q30. If the last cycle is particular bad then the two values will be very different from each other.
I can confirmed this by restricting the cycle to the prior cycle of read in analysis tab and the Q metric would then be identical to the result in summary tab.
Is there any reason that it will skip last cycle when summarzing Q30? Or is the analysis tab in SAV/dumptext correct and the summary needs t obe fixed?

**Comment by ezralanglois** [comment]
Hi Yechen Qiao,

This is a known discrepancy, which we should have, at minimum, documented clearly and did not. The cycle-based metrics in the summary chart, e.g. error, q30, yield, are computed over “useable cycles”. A usable cycle is one that is fully corrected in terms of phasing/prephasing. We don’t consider the last cycle of a run as usable, because it is not fully corrected. So, we don’t count this cycle toward yield or % >= q30 or error rate. Many aligners drop the last cycle for this reason.

The analysis chart shows all cycles for every plot (otherwise we introduce a new inconsistency between plots). The dumptext algorithm also provides data for all cycles, which coincides well with its purpose.

This is mostly addressed here in the InterOp documentation: http://illumina.github.io/interop/calculated_metrics.html

We will work to better address this issue in the documentation.

Best,
Rob

**Comment by yechenqiao** [comment]
Hi Rob,
Thanks for your quick response. Removing the last cycle fixed it for me =)

**Comment by ezralanglois** [comment]
I updated the documentation to reflect the question. Closing this out.
