### ISSUE TITLE
Problems installing python module

### ISSUE THREAD

**Issue by olingerc** [Illumina/interop#117]
I tried following the instructions for python installation:
On the `https://github.com/Illumina/interop/releases/tag/v1.0.18` page the pip installation is described as follows:
`pip install -f https://github.com/Illumina/interop/releases/latest interop`
The output on my ubuntu 16.04 machine is: 
```
Could not find a version that satisfies the requirement interop (from versions: linux_gcc46_release, mingw_win64_Release, msvc14_win64_Release, osx_clang_release)
No matching distribution found for interop
```

On the `http://illumina.github.io/interop/python_binding.html` page it says:
`pip install -f https://ussd.artifactory.illumina.com/list/generic-bioinformatics/interop/pypi/ interop`
but my proxy server seems to have problems with the SSL certificate

I proceeded to donwload the wheel package:
`interop-1.0.18-cp27-cp27mu-linux_x86_64.whl`
Trying to pip install it I get:
```interop-1.0.18-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.```

My platform:
```Linux x86_64 x86_64 GNU/Linux```

Would you have any suggestions on how to proceed?

**Comment by ezralanglois** [comment]
Hi,

Ignore that second artifactory url, that should not have been posted.

The most likely reason the wheel is not working is that the version of Python I used to create it is using a different from the version of Python in some small way. My first guess would be the unicode support. I already ran into that issue once.

To build these wheels on travis and appveyor, I currently use Anaconda, not the ubuntu system Python.

I will be out for the rest of this week, but I can take a look next week to see if we can build with that on travis.

The workaround I have been using when encountering this problem is to build the wheel locally.

`mkdir build`
`cd build`
`cmake ../`
`cmake --build . --target package_wheel`

Then pip install the built wheel. It would be interesting to see what the name of your wheel turns out to be, that is determined by the OS and characteristics of Python.

Best,
Rob

**Comment by olingerc** [comment]
Thanks Robert. I'll build from source in the meantime.

**Comment by olingerc** [comment]
Manually builidng in a python3 virtualenv and installing with pip works fine. Here's my environment:
```
Linux 4.4.0-66-generic #87-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

cmake version 3.5.1
Python 3.5.2
SWIG Version 3.0.8
```
And the wheel with current interop master
`interop-1.0.18.dev6-cp35-cp35m-linux_x86_64.whl
`

**Comment by ezralanglois** [comment]
Hi,

I dug into this a little bit. We have not gotten around to testing python 3 support. It looks like the exceptions will not work because we used a metaclass workaround to some problems we ran into with SWIG exceptions. Fixing the root cause of the problems should get them to work in both versions of Python.

Also, I would like to limit the number of Python versions we support, I think 2.7 and 3.6 would cover most cases.  What are you thoughts on this?

Best,
Rob

**Comment by olingerc** [comment]
Hi Rob,
Concerning the supported Python versions I agree it would be best to limit to as few as possible. I have only one concern: People that use Ubuntu in a production environment tend to stick to the LTS versions. The latest is 16.04 which will be supported until 2021. However, this only has Python 3.5.2 and they most likely will not update to 3.6.x. This will only happen with the next LTS release due in April 2018. On the other hand. Ubuntu users might not be the majority in our field of study.

Ultimately it is of course your choice, but I would include 3.5 in your automated testing. I think travis can do that.

Concerning Python 3 support, I have not encountered any issues with InterOp in my Python 3.5.2 environment, so good job there!

**Comment by jbsysadmin** [comment]
A question on this: how does  one execute "cmake --build . --target package_wheel?"
On my attempt, I got "No rule to make target `package_wheel."'

**Comment by ezralanglois** [comment]
That happens when Cmake cannot find Python. If you check the log during the configuration step: `cmake ../', you will see either Python Interpreter, Python Libraries or NumPy was not found.

Fix that issue first, and then the package_wheel target should be available.

**Comment by ezralanglois** [comment]
Hi Christophe,

Feel free to open another ticket if this Python distribution does not work for you. 3.5 should be available.

Best,
Rob

**Comment by jbsysadmin** [comment]
Thanks for reply! Python lib and bin directories were in PATH at the time. Was there some other means to make them available to cmake?

**Comment by ezralanglois** [comment]
Could you post the Cmake log after you run configure `cmake ../`?

**Comment by jbsysadmin** [comment]
-- InterOp v1.0.16
CMake Warning at src/ext/CMakeLists.txt:11 (message):
  Swig version 1 found, but version 3.x or later is required.  Skipping
  interface generation.
-- Could NOT find CSharp (missing:  CSHARP_TYPE CSHARP_VERSION CSHARP_COMPILER)
-- GTest include directory not found
-- Enable Shared CRT for GTest
-- Could NOT find GTest (missing:  GTEST_LIBRARY)
-- GMock include directory not found
-- Could NOT find GMock (missing:  GMOCK_LIBRARY)

**Comment by ezralanglois** [comment]
Let's move this over to https://github.com/Illumina/interop/issues/120 so we are not spamming Christophe. I will answer there.
