### ISSUE TITLE
MacOSX *.so files refer to @rpath which does not exist

### ISSUE THREAD

**Issue by tcezard** [Illumina/interop#127]
I installed interop python wheel file on my mac using
```
pip install -f https://github.com/Illumina/interop/releases/latest interop
```
against a virtualenv created from a manally installed python
(BTW this only works with python 3.6 because there are no other wheel)

When I use it I get a stack trace.
```
ImportError: dlopen(/Users/tcezard/python/python-analysis-driver/lib/python3.6/site-packages/interop/_py_interop_run_metrics.so, 2): Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/tcezard/python/python-analysis-driver/lib/python3.6/site-packages/interop/_py_interop_run_metrics.so
  Reason: image not found
```
The `.so` files refers to an `@rpath` which is not defined. From what I can read it seems to be related to anaconda but I'm not using anaconda to install python or my venv.
I could fix this by manually editing the .so files as follow
```sh
for i in *.so
do 
    install_name_tool -change "@rpath/libpython3.6m.dylib" /Library/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib $i
done
```
Is it something that can be fix on you end so I do not have to tinker with the `.so` files?
Is there another way of installing that should be preferred ?

**Comment by ezralanglois** [comment]
Hi Timothee,

Thanks for reporting the problem. The main issue is that we built these wheels using a version of Python that was linked to a shared library. We recently fixed this issue in Linux by using a manylinux docker image that has Python preinstalled in such a way that there is no shared library.

We have not done the same with OSX yet, because we need to setup a travis script that properly installs each version of Python from source (or find a prebuilt solution that fits this no shared library requirement).

This will take some time to fix, but we do plan a fix. I will leave this ticket open until we do.

Also, is there a big need for Python 3.4 or 3.5 on a Mac? I am not that familiar with Python 3.x. I was planning on dropping support for 3.4 and 3.5 on Mac and Windows (keeping it on Linux is trivial with the docker image we are using).

Best,
Rob

**Comment by tcezard** [comment]
Thanks Rob,
We can use 3.6 for development on our macs but our production (on linux) is running 3.4. It would be better to keep using the same environment if possible but not mandatory.

**Comment by ezralanglois** [comment]
I believe I fixed the problem in the Mac build. I tried it out on my mac and it seemed to work fine, but I am not sure I have the same setup. If you have a chance and would like to test it out, I would appreciate it.   You can install it from here:

`pip install -f https://github.com/ezralanglois/interop/releases/tag/v9.9.9.16 interop`

I plan to create an official release with these changes soon. This should include a Python 3.4 build too.

Best,
Rob

**Comment by tcezard** [comment]
Thanks Rob, that's awesome.
I tested 3.6 and 3.4 and they both work!
Cheers
Tim

**Comment by ezralanglois** [comment]
No problem. Turned out to be easier than I originally suspected.
I will close this issue out once this goes into master (after some more testing) and then create a new official release.
Best,
Rob
