### ISSUE TITLE
IndexMetricsOut.bin source and regeneration

### ISSUE THREAD

**Issue by larskoenig-rtl** [Illumina/interop#134]
We receive data from a sequencing center that does not generate fastq data. Once we create a tag sheet here and generateFASTQ with our local copy of MiSeq Reporter the IndexmetricsOut.bin file is generated. If the file is incorrect e.g. the i7 is the wrong orientation, the SAV Indexing metrics are wrong and will not correct themselves when the SampleSheet is fixed and generateFASTQ is rerun. How can this file be updated to a new SampleSheet?

We also regularly rerun our MiSeq runs to generate Index files to check for tag errors, which 1) takes time to generate the files and 2) takes time to parse the index files, lots of time in the case of HiSeq runs. What files contain the data used to generate the IndexMetricsOut.bin file? I need to know the physical tag combinations, so I can't use the DemultiplexSummary files since it does not contain the pairing information.

**Comment by ezralanglois** [comment]
Hi,

Let me start off by saying that most of the question can probably be better handled by [Illumina Technical Support](https://www.illumina.com/company/contact-us.html), but I will give it a shot.

When you convert from BCL to FASTQ, you are simultaneously performing a step called [demultiplexing](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq_letterbooklet_15038058brpmi.pdf). This is a reorganization of the data based on the index sequences contained in the BCLs.

Now, SAV (which uses the InterOp Library) only reads an output from generateFASTQ: IndexMetricsOut.bin. The reason the SAV results do not change could be due to a file lock or saving issue, such that the IndexMetricsOut.bin does not update. There could be another issue, in which case Illumina Technical Support is the best place to pursue this issue.

Best,
Rob
