### ISSUE TITLE
Indexing QC metrics (Python)

### ISSUE THREAD

**Issue by angsm** [Illumina/interop#146]
Hi Illumina,

May I know if there is a way to use python interop library to display the indexing QC "% aligned to index"? I realized that the examples given in the documentations are all by lane or tile.

Thank you
Shimin Ang

**Comment by ezralanglois** [comment]
Hi Shimin,

Are you talking about the % of Reads Identified on the SAV Indexing Tab? It sounds like you are, but I just wanted to make sure. 

We don't average it for the run because some of the flowcells for certain sequencers have individually addressable lanes, and we don't have a fool proof way to determine whether the flowcell has the same set of samples in each lane.

For your application if you know this is not the case, then you can just average the numbers over all lanes.

**Comment by angsm** [comment]
Hi Robert,

Yup, sorry about the confusion, its “% of Reads Identified”, could you kindly point me to the documentation where this is mentioned?

Thank you!

Regards
Shimin Ang

**Comment by ezralanglois** [comment]
Hi Shimin,

We don't have great documentation on this at the moment. I will work on fixing this for the future (and leave this question open until it is fixed).

`total_fraction_mapped_reads` maps to `% Reads Identified (PF)` in SAV. You can find it in the `index_lane_summary` here:
https://github.com/Illumina/interop/blob/51eb4ca8b2918b03e2c71d7c6d57a37914d9d0c3/interop/model/summary/index_lane_summary.h#L193


Basically, to get the information you require you need to populate either the `index_flowcell_summary`. You can do that in a manner very similar to the [summary example here](https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_01_Intro.ipynb). Just replace run_summary with one of the aforementioned objects and call `summarize_index_metrics` instead of `summarize_run_metrics`.

Here is an example in C++ which is very similar
https://github.com/Illumina/interop/blob/master/src/apps/index_summary.cpp#L110

Also, I had forgotten that as of the latest release 1.0.25, we do support aggregating over all lanes in certain special cases.

The interface is a little different to do this (it is very new support).

If you pass in 0, instead of a lane number (>=1), then it aggregates over all lanes
summarize_index_metrics(run_metrics_object, 0, index_lane_summary_object);

You cannot get this information if you use the `index_flowcell_summary`.

**Comment by ezralanglois** [comment]
I just updated the documentation to address these issues. 

Closing this out, feel free to reopen if you have further questions on this topic.

**Comment by angsm** [comment]
Hi ezralanglois,

I tried the example you mentioned and got '0', I am not sure if its working.

```
from interop import py_interop_run_metrics, py_interop_run, py_interop_summary
run_metrics = py_interop_run_metrics.run_metrics()

valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
run_folder = run_metrics.read(run_folder, valid_to_load)

summary = py_interop_summary.index_lane_summary()
py_interop_summary.summarize_index_metrics(run_metrics,0,summary)
print (summary.total_fraction_mapped_reads())
```

To clarify, I am trying to get the values as below, the first image is by index and the second by per lane:
![image](https://user-images.githubusercontent.com/10956184/31600187-12b0fe10-b288-11e7-99a7-631b5ec86ee5.png)
![image](https://user-images.githubusercontent.com/10956184/31600218-3128a4a6-b288-11e7-85d3-1f427910e80f.png)


Would you point me to the updated documentation you mentioned? My apologies for the delayed reply as I was away.

Thank you.
Shimin Ang

**Comment by ezralanglois** [comment]
Hi Shimin,

The example code you have is almost correct, but you need to replace
`py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)`
with
`py_interop_run_metrics.list_index_metrics_to_load(valid_to_load)`

The first one lists all InterOp files that are required by the summary tab, the second by the Indexing tab. You are getting zero because the proper InterOp file was not loaded.

Best,
Rob

**Comment by ezralanglois** [comment]
Also I added the following to the documentation (under modules):
http://illumina.github.io/interop/group__index__flowcell__summary.html

**Comment by nudpa** [comment]
Closing out - please feel free to reopen if there are further questions
