### ISSUE TITLE
Python example for number of reads by index

### ISSUE THREAD

**Issue by olingerc** [Illumina/interop#167]
Hi Robert,
I am trying to get a table showing the number of reads by index using the python interface. I manage to get total reads and reads passing filter, but how would I get reads per index? I currently have:
```python
from interop import py_interop_run_metrics, py_interop_run, py_interop_summary
run_metrics = py_interop_run_metrics.run_metrics()

valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_index_metrics_to_load(valid_to_load)
run_metrics.read(path_to_run, valid_to_load)

summary = py_interop_summary.index_lane_summary()
py_interop_summary.summarize_index_metrics(run_metrics, 0, summary)
total_reads_pf = summary.total_pf_reads()
total_reads = summary.total_reads()
```

Thanks for your help on this.

**Comment by ezralanglois** [comment]
Hi,

Here is an example of what you want to do:
https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_04_Indexing_Metrics.ipynb

Everything [index_lane_summary](http://illumina.github.io/interop/group__index__lane__summary.html) has a collection of [index_count_summary](http://illumina.github.io/interop/group__index__count__summary.html)s. There is one `index_count_summary` per index sample.

Best,
Rob

**Comment by tcarlile** [comment]
Hi Ezra,
This is pretty much exactly what I want to do, however I'm getting an error. I'm using the BaseSpace python API to download the binary and xml files for the runs that I want. The code is below, where runs is a list of BaseSpacePy run objects. I've added a few print statements for checks.

`for run in runs:
                run_folder = str(run)
                print os.path.exists(run_folder)
                run_metrics = py_interop_run_metrics.run_metrics()
                valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
                py_interop_run_metrics.list_index_metrics_to_load(valid_to_load)
                run_folder = run_metrics.read(run_folder, valid_to_load)
                print type(run_folder)
                summary = py_interop_summary.index_flowcell_summary()
                py_interop_summary.summarize_index_metrics(run_metrics, summary)
                lane_summary = summary.at(0)`

The output from the print statements:
`True
<type 'NoneType'>`

The traceback:
`Traceback (most recent call last):
  File "run_qc_summary.py", line 63, in <module>
    main(sys.argv[1:])
  File "run_qc_summary.py", line 42, in main
    lane_summary = summary.at(0)
  File "/camhpc/pkg/python/2.7.11/centos6/lib/python2.7/site-packages/interop/py_interop_summary.py", line 952, in at
    return _py_interop_summary.index_flowcell_summary_at(self, n)
interop.py_interop_metrics.index_out_of_bounds_exception: Lane index exceeds lane count - 0 >= 0
/io/./interop/model/summary/index_flowcell_summary.h::operator[] (63)
`
I've checked the md5sums for a few files downloaded from the web, and via the API. I'm not sure what the issue is.

Best,
Thomas

**Comment by ezralanglois** [comment]
Hi Thomas,

There was a bug in the example
`run_folder = run_metrics.read(run_folder, valid_to_load)`
should be
`run_metrics.read(run_folder, valid_to_load)`

This causes the second print to be `<type 'NoneType'>`

As for the exception, it is possible that your run folder is missing `IndexMetricsOut.bin`.

**Comment by tcarlile** [comment]
Hi Rob,
Thanks for the quick response. The `IndexMetricsOut.bin` files are being downloaded.

Adding:
`fn = run_folder+'/IndexMetricsOut.bin'`
`print fn, os.path.exists(fn)`

Yields:
`171121_D00606_0160_ACBVTKANXX/IndexMetricsOut.bin True`

The files are downloaded for several other runs I've tested.

Best,
Thomas

**Comment by ezralanglois** [comment]
Based on your example, it appears the InterOp files are being downloaded into the wrong folder.

The InterOp Files should be in a subdir called InterOp. 

If an InterOp file is missing, then we do not throw an error. 

Best,
Rob
