### ISSUE TITLE
Data By Cycle / Q30 / average

### ISSUE THREAD

**Issue by markliresbio** [Illumina/interop#241]
Hi,
When we have reagent or local FC issues, we can see "snow" in SAV. Would be great to recreate using plot_by_cycle.

In SAV, with % >=30, Lane: All, Surface All, it looks like this:
![image](https://user-images.githubusercontent.com/43545972/100494771-bd8c2380-30f9-11eb-8124-b36c964246d6.png)
In the run, there are a few dead tiles causing low Q30 and the snow.

Using plot_by_cycle --metric-name=Q30Percent, I get box plots, but I think I want average.
![image](https://user-images.githubusercontent.com/43545972/100494724-3ccd2780-30f9-11eb-8504-44b76bf1ec2f.png)
No Snow! 

Any help appreciated.

Thanks,

Mark

**Comment by ezralanglois** [comment]
Hi Mark,

We use these command line apps to show how to use the InterOp library. Unfortunately, GNUPLOT has some limitations we were not able to work around. We could not display the outliers using the plot data provided by InterOp (the candle stick plot was the closest).

You could use the `imaging_table` command line app and add use the GNUPlot [boxplot](http://gnuplot.info/demo_5.2/boxplot.html) command. The only disadvantage of this approach is that you may not get the exact same box plot in terms of outliers and quantiles as SAV because now you are relying on the GNUPLOT box plot logic.

Best,
Rob

**Comment by markliresbio** [comment]
Hi Rob, Thanks for the quick response.
Do any of the command line tools export out the outlier Q30s?
thanks,
Mark
