### ISSUE TITLE
InterOp python library incorrectly reporting NovaSeq flowcell surfaces count

### ISSUE THREAD

**Issue by ppswang** [Illumina/interop#280]
Hi, 

I have a set of NovaSeq 6000 flowcell data that was provided to me by Illumina.

This looks to be an SP flowcell:
```
RunParameters.xml:    <FlowCellMode>SP</FlowCellMode>
RunParameters.xml:    <ClusterSupportedModes>SP</ClusterSupportedModes>
```
The number of tiles reported in RunInfo.xml is 312, which matches the specifications for SP flowcell. 
According to the specs, the number of surfaces should be 1 for a SP flowcell. 

However, when I tried to get this information with the following:

```
from interop import py_interop_run
run = py_interop_run.info()
run.read(FCDIR)
interop_fc = run.flowcell()

```
`interop_fc.surface_list()` returned `(2,)` while `interop_fc.surface_count()` returned `2`

**Comment by ezralanglois** [comment]
This is due to a limitation in our legacy plotting library. We label each surface 1 and 2, if only surface 2 is scanned, then we still report the surface count as 2.

This logic could be moved downstream. Really, getting the length of the surface list is a better way to determine the number of surfaces.
