### ISSUE TITLE
Function percent_phasing() in interop2csv

### ISSUE THREAD

**Issue by rglandie** [Illumina/interop#30]
hello, 

I use script interop2csv to obtain some metrics about run, but i think have a problem in function percent_phasing which is use in interop2csv. For read 3 (read 1 = first read read2 = index read read3= second read) the percent_phasing is always 0. For read 1 the percent _phasing equals to percent_phasing for read 3 observed in Illumina Sequencing Analysis Viewer. Is it possible that exists a problem in this function ?

Romain

**Comment by ezralanglois** [comment]
Hi Romain,

We recently released a bug fix that sounds a lot like the bug you are describing. 

http://illumina.github.io/interop/changes.html

It would help immensely if you can let me know which version of InterOp you are using. It should be printed at the end of the output for interop2csv.

Rob

**Comment by rglandie** [comment]
I Rob, 

I use version # Version: v1.0.1-44-gcae8888-dirty

I have another problem with function : totalReads() in Module Error Metrics. The value given by this function is always 0. 


Romain

**Comment by ezralanglois** [comment]
Hi Romain,

Thanks for getting back to me on the version. Just to make sure we are on the same page, the latest version is 1.0.3, which has the bug fix you described in your last post (master also has the bug fix).

As for the totalReads, this is a bug. It was deprecated on all modern platforms and we don't test this anymore. I will put out a bug fix, so this reports the proper number for older platforms.

As a temporary workaround, you can compute this number by summing over mismatch_cluster_count (this will only work for legacy platforms).

Alternatively, for all platforms, this number is reads PF (number of PF clusters) times percent aligned. So you can compute this from tile metrics.

**Comment by ezralanglois** [comment]
Hi Romain,

After reviewing this field, we realized the best thing to do was just remove it. It fell through the cracks and should never have been included. It is better to have a solution that works on all platforms rather than just a few legacy ones.

I will remove it from the model and interop2csv in the next update to master.

**Comment by ezralanglois** [comment]
This is the pull request that will remove this item: 
https://github.com/Illumina/interop/pull/31

It will be going into master for now.

**Comment by rglandie** [comment]
Hi Robert,

Thanks for answers. if i understand you delete function totalReads() definitively ? 
Have you an idea about time to have function to calculate % read >=Q30 ? 

Romain

**Comment by ezralanglois** [comment]
It is being worked on right now. I am doing it in stages, I just checked in the ability to read the RunInfo.xml, which provides the read structure. 

Next, I plan to create a single run_metrics class that contains all the individual metrics.
After that, I will add the model for the summary tab in SAV
Finally, I will add the logic to do the calculations for all the summary metrics. 

I cannot give a definitive timeline right now, because I am working on several other projects.

**Comment by ezralanglois** [comment]
As for totalReads, I did delete it. First, because it has not been supported by the InterOp since the GA-days and we are not supporting GAs. The older versions of SAV (for HiSeq and MiSeq) reported this number using tile metrics as I described above.
The fields in this part of the InterOp model should only support values read from the files and not calculated from other metrics.
