### ISSUE TITLE
[question]: Understanding interop_index-summary usage and different csv outputs

### ISSUE THREAD

**Issue by tamuanand** [Illumina/interop#345]
I am using bcl-convert 4.2.7 and then interop_index-summary to have a look at the results : https://illumina.github.io/interop/index_summary.html

When I use  interop_index-summary <path_to>/SAV_DIR --csv=1 

```
Lane 1
Index Number,Sample Id,Project, Index 1 (I7),Index 2 (I5),% Read Identified (PF)
1, <other_data>
2,
…
10
Lane 2 
Index Number,Sample Id,Project, Index 1 (I7),Index 2 (I5),% Read Identified (PF)
1, <other_data>
2,
..
10
```

Some questions:

[Q1] Does it give more than 2 lanes
[Q2] When does one use –-csv=1or –-csv=2 or -–csv=3  
[Q3] What are the key differences between these? Are there docs around this
[Q4] What are all the different ways one can get the csv data parsed

**Comment by ezralanglois** [comment]
First be aware that bclconvert deprecated the IndexMetricsOut.bin in favor of several new CSV files.

I am not sure when it starts, but at some point, by default, bclconvert will no longer write out the relevant files unless a command line argument is given.

1. Depends on the input to bclconvert. It can if the input supports multiple lanes to a single output directory
2. It supports 0 (default) CSV format, otherwise it writes out white space separated.
3. No documentation, normally the default is used
4. I don't understand this question.
