### ISSUE TITLE
MiSeq QScores / NextSeq current Cycle

### ISSUE THREAD

**Issue by markliexo** [Illumina/interop#52]
Thank you for putting together this software its great!

I am trying to build a watcher for runs in process using your summary script. I noticed a few things:

1. MiSeq - the QScores are 100% which obviously isn't reflected in the data.
2. NextSeq & MiSeq - the clusterPF gets written for both reads as soon as Read1 data is availabe. Is this normal?

I use the Recipe/RunSate.xml on the MiSeq to extract the current step and cycle. I've been told by Illumina that that information is available in one of the InterOp files. It would be great if your summary script to access that information and display.

Thank you!

**Comment by ezralanglois** [comment]
Hi Mark, 

Great to hear you like the library. 

I am going to separate the "MiSeq - the QScores are 100% which obviously isn't reflected in the data." into another issue. Please respond to this issue in this thread: https://github.com/Illumina/interop/issues/53

It would help to know when you are seeing 100%, during the run, end of run and such? Also, could you attach an example Q-metric Interop file with a RunInfo.xml to the newly created issue? It would really help to figure out the problem.

**NextSeq & MiSeq - the clusterPF gets written for both reads as soon as Read1 data is availabe. Is this normal?**

Yes. The PF is the same between read 1 and every read after.

**MiSeq to extract the current step and cycle**

This is available in the InterOp files under the following conditions:
1. It may be lagging behind the sequencer depending on when it is flushed to disk
2. The MiSeq workflow is different from most other sequencers. It will perform extraction on as many tiles as possible, before going back and basecalling.
3. If you are reading these files from a network drive, rather than on instrument, then there may be other delays depending on the run copy service.

SAV generally reports three state numbers:
- Last cycle extracted
- Last cycle basecalled
- Last cycle q-scored

For MiSeq, you will see the last cycle extracted may be much later than the last cycle base called. For most other sequences, all three will be less divergent. 

Right now, the summary logic provides the last cycle error rated. You can access that in either the lane summary or the run_summary  from the cycle_state method. The error_cycle_range is the only one currently populated. 

The start of the range is the latest cycle where all tiles have been error rated, where as the end of the range is latest cycle that any tile has been error rated. 

I created another issue https://github.com/Illumina/interop/issues/54 to populate the other cycle states. If you have further questions on this topic, please use this thread.

Best.

**Comment by ezralanglois** [comment]
I am closing this out. There are two outstanding issues that were raised by this, which will stay open.
